version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 99
  commit-message:
    prefix: chore
    include: scope
