image: node:8

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - if [ $BITBUCKET_BRANCH == 'master' ]; then
          - yarn --frozen-lockfile
          - yarn build
          - yarn global add firebase-tools
          - firebase deploy --token=$FIREBASE_TOKEN --non-interactive
          - fi
