name: CI

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      #      - name: check for Conventional Commits
      #        id: check-for-cc
      #        uses: agenthunt/conventional-commit-checker-action@v1.0.0
      - run: yarn install
      - run: yarn prettier
      - run: yarn build

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Python '3.7'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install Required Python Modules
        run: |
          python -m pip install --upgrade pip
          pip install -r .requirements
      - name: Commit Lint
        run: |
          gitlint --commits 'main..HEAD'
